### ISSUE TITLE
Temp bans won't lift

### ISSUE THREAD

**Issue by hounddogie** [1day2die/ULX-Global-Ban-Fix#17]
![image](https://github.com/1day2die/ULX-Global-Ban-Fix/assets/85585283/8b25eef4-6a34-4b89-957a-698ad5ae5475)
I banned myself via "!ban ^ 1h skeleton nuts" and i am just getting back on to find the ban didn't life and the time is now just empty on the ban screen.

**Comment by hounddogie** [comment]
That was 12:37 AM, it is 12:42 PM.

**Comment by Bryantdl7** [comment]
[ulx_globalbanmodule] addons/ulx_globalbanmodule/lua/globalban/gb_banmanagement.lua:232: attempt to compare number with nil   1. fn - addons/ulx_globalbanmodule/lua/globalban/gb_banmanagement.lua:232    2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
