### ISSUE TITLE
Implement error checking for if server is offline

### ISSUE THREAD

**Issue by Bryantdl7** [1day2die/ULX-Global-Ban-Fix#5]
When rebooting our dev server, the following errors are thrown: 

![image](https://user-images.githubusercontent.com/5564661/221226126-a1fba35b-abe7-4ec9-a497-7882e213ef03.png)

This was caused by me manually adding the servers to the server list of the database, if there is a better way definitely let me know!

**Comment by Bryantdl7** [comment]
This also causes issues for NATed dev servers using RFC1918 addresses, as a public facing web server cannot query a local IP. 
![image](https://user-images.githubusercontent.com/5564661/221232447-c53a313f-db7a-493e-bcdd-45c5915fb6b8.png)

**Comment by 1day2die** [comment]
Disabling php warnings in your php.ini is a hotfix for this

**Comment by 1day2die** [comment]
fixed
