### ISSUE TITLE
Modern theme queries incorrect SQL rows

### ISSUE THREAD

**Issue by Bryantdl7** [1day2die/ULX-Global-Ban-Fix#6]
e.g. SteamID queries BanID

![image](https://user-images.githubusercontent.com/5564661/221232957-7d34e4ea-e88f-4984-a95d-8a26c54c3ff4.png)

![image](https://user-images.githubusercontent.com/5564661/221233139-65f0dfad-c099-4d30-90d5-7a81f679a14e.png)

**Comment by Bryantdl7** [comment]
Appears this is the error it throws 



<b>Warning</b>:  Undefined variable $tmp in <b>/usr/www/darkstorm/darkstorm/bans/lib/functions.php</b> on line <b>11</b><br />
--
  | <br />
  | <b>Fatal error</b>:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable\|array, null given in /usr/www/darkstorm/darkstorm/bans/lib/functions.php:11
  | Stack trace:
  | #0 /usr/www/darkstorm/darkstorm/bans/index.php(155): calcSteamID()
  | #1 {main}
  | thrown in <b>/usr/www/darkstorm/darkstorm/bans/lib/functions.php</b> on line <b>11</b><br />

**Comment by 1day2die** [comment]
did you add the ban by hand? The SteamID seems Short and the Name is missing?

**Comment by 1day2die** [comment]
couldnt reproduce

**Comment by Bryantdl7** [comment]
I did not add this ban by hand, I added it using ulx xban for a steamid. The steamID I like to use for testing is Garry, because who else would we target for ban testing :)

**Comment by Bryantdl7** [comment]
Here's a copy of my database if you want to see if that helps to repro. Rename to .sql to import using phpmyadmin or other sql solution 
[darkstorm_globalban_2023.txt](https://github.com/1day2die/ULX-Global-Ban-Fix/files/10841533/darkstorm_globalban_2023.txt)

**Comment by 1day2die** [comment]
fixed
