### ISSUE TITLE
dark theme - Undefined variable $tmp in /bans/lib/functions.php on line 12

### ISSUE THREAD

**Issue by Bryantdl7** [1day2die/ULX-Global-Ban-Fix#8]
Error found within the dark theme: 

<b>Warning</b>:  Undefined variable $tmp in <b>/usr/www/darkstorm/darkstorm/bans/lib/functions.php</b> on line <b>12</b><br />
--
  | <br />
  | <b>Fatal error</b>:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable\|array, null given in /usr/www/darkstorm/darkstorm/bans/lib/functions.php:12
  | Stack trace:
  | #0 /usr/www/darkstorm/darkstorm/bans/index.php(161): calcSteamID()
  | #1 {main}
  | thrown in <b>/usr/www/darkstorm/darkstorm/bans/lib/functions.php</b> on line <b>12</b><br />

This error also makes the webpage fail to populate bans appropriately: 

UI: 
![image](https://user-images.githubusercontent.com/5564661/221236200-561f96b8-4d77-4ee3-9225-6cb1e17a31c5.png)

SQL entry: 
![image](https://user-images.githubusercontent.com/5564661/221236246-c514c20e-9833-4159-b9bb-e2bbb5c1b099.png)

**Comment by 1day2die** [comment]
did you add the ban by hand? The SteamID seems Short and the Name is missing?

**Comment by 1day2die** [comment]
fixed
