### ISSUE TITLE
.env protection does not exist - SQL password breach guaranteed

### ISSUE THREAD

**Issue by Bryantdl7** [1day2die/ULX-Global-Ban-Fix#9]
Since no .htaccess or other methods are configured users can manually navigate to the generated .env file and view the plaintext SQL username and password. this is a massive security vulnerability that anyone that isn't a well versed admin could overlook and be pwned hard

confirmed on the dark and modern themes, light theme has the password hardcoded into php code, so it isn't affected.

**Comment by 1day2die** [comment]
Thanks, this file was never uploaded.
